
services:
  main_service:
    build: ./main_service
    container_name: main_service
    ports:
      - "5000:5000"  # Ова значи дека портата 5000 на локалниот компјутер ќе биде мапирана на портата 5000 на контејнерот
    depends_on:
      db:
        condition: service_healthy
      data_fetcher_service:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://youradminuser%40myuniquepostgresserver:YourStrongPassword%21%23123@myuniquepostgresserver.postgres.database.azure.com/postgres?sslmode=require
    volumes:
      - ./data:/app/data
    networks:
      - app_network

  data_fetcher_service:
    build: ./data_fetcher_service
    container_name: data_fetcher_service
    ports:
      - "5001:5001"  # Ова значи дека портата 5001 на локалниот компјутер ќе биде мапирана на портата 5001 на контејнерот
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s

  visualization_service:
    build: ./visualization_service
    container_name: visualization_service
    ports:
      - "8050:8050"  # Ова значи дека портата 8050 на локалниот компјутер ќе биде мапирана на портата 8050 на контејнерот
    depends_on:
      main_service:
        condition: service_started
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: database
    restart: always
    ports:
      - "5432:5432"  # Ова е порта во која ќе се мапира дата базата
    environment:
      POSTGRES_DB: mse_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrongPassword%21%23123
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mse_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge
